CREATE DATABASE BD_BANCO_TCC;

USE BD_BANCO_TCC;

CREATE TABLE CONTAGEM_ALUNOS(
ID INTEGER AUTO_INCREMENT PRIMARY KEY,
PERIODO VARCHAR(10)NOT NULL,
QUANTIDADE_LANCHE_MANHA INTEGER NOT NULL,
QUANTIDADE_BEBIDA_MANHA INTEGER NOT NULL,
QUANTIDADE_LANCHE_TARDE INTEGER NOT NULL,
QUANTIDADE_BEBIDA_TARDE INTEGER NOT NULL,
TURMA VARCHAR(10) NOT NULL,
DATA DATE NOT NULL
);

ALTER TABLE CONTAGEM_ALUNOS
MODIFY COLUMN TURMA VARCHAR(30) NOT NULL;

ALTER TABLE CONTAGEM_ALUNOS
DROP COLUMN PERIODO;

CREATE TABLE restricoes_alimentares (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome_aluno VARCHAR(255) NOT NULL,
    telefone_responsavel VARCHAR(50) NOT NULL,
    tipo_restricao VARCHAR(255) NOT NULL,
    turma VARCHAR(50) NOT NULL,
    nome_profissional VARCHAR(255) NOT NULL,
    registro_profissional VARCHAR(100) NOT NULL,
    anotacoes_sintomas TEXT NOT NULL,
    documento_medico VARCHAR(255),
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

SELECT * FROM restricoes_alimentares;


DROP TABLE RESTRICOES_DIETAS;

CREATE TABLE ADMINISTRADOR(
CPF VARCHAR(11)NOT NULL,
 TIPO VARCHAR(50) NOT NULL,
 NOME VARCHAR(100) NOT NULL,
 EMAIL VARCHAR(150) NOT NULL,
 UNIDADE_ESCOLAR VARCHAR(100) NOT NULL,
 SENHA VARCHAR(150) NOT NULL
);
ALTER TABLE ADMINISTRADOR DROP COLUMN TIPO;
ALTER TABLE ADMINISTRADOR MODIFY COLUMN CPF VARCHAR(20) PRIMARY KEY;

CREATE TABLE DESPERDICIO(
ID  INTEGER AUTO_INCREMENT PRIMARY KEY,
DESPERDICIO_KG VARCHAR(50) NOT NULL,
RA VARCHAR(4) NOT NULL
);

ALTER TABLE DESPERDICIO
ADD COLUMN data_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP;


ALTER TABLE DESPERDICIO
ADD COLUMN DESPERDICIO_DIARIO VARCHAR(50) NOT NULL,
ADD COLUMN DESPERDICIO_SEMANAL VARCHAR(50) NOT NULL,
ADD COLUMN DESPERDICIO_MENSAL VARCHAR(50) NOT NULL;

ALTER TABLE DESPERDICIO DROP COLUMN DESPERDICIO_KG;

ALTER TABLE DESPERDICIO
MODIFY COLUMN DESPERDICIO_DIARIO DECIMAL(10,2) NOT NULL,
MODIFY COLUMN DESPERDICIO_SEMANAL DECIMAL(10,2) NOT NULL,
MODIFY COLUMN DESPERDICIO_MENSAL DECIMAL(10,2) NOT NULL;
TRUNCATE TABLE DESPERDICIO;
CREATE TABLE REFEICAO(
id INT AUTO_INCREMENT PRIMARY KEY,
quantidade_diaria INT NOT NULL,
quantidade_semanal INT NOT NULL,
quantidade_mensal INT NOT NULL,
data_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE REFEICAO DROP COLUMN quantidade_semanal;
ALTER TABLE REFEICAO DROP COLUMN quantidade_mensal;

insert into refeicao(quantidade_diaria,quantidade_semanal,quantidade_mensal)
values
(80,0,10);

ALTER TABLE REFEICAO ADD COLUMN cpf_usuario VARCHAR(20);
ALTER TABLE DESPERDICIO ADD COLUMN cpf_usuario VARCHAR(20);
ALTER TABLE CARDAPIO ADD COLUMN cpf_usuario VARCHAR(20);
ALTER TABLE restricoes_alimentares ADD COLUMN cpf_usuario VARCHAR(20);
ALTER TABLE contagem_alunos ADD COLUMN cpf_usuario VARCHAR(20);

INSERT INTO DESPERDICIO
(DESPERDICIO_DIARIO, DESPERDICIO_SEMANAL, DESPERDICIO_MENSAL, RA, data_registro, cpf_usuario)
VALUES
("10.55", "10.12", "15.00", "1878", "2025-06-24", "12345678923");

INSERT INTO REFEICAO
(quantidade_diaria, quantidade_semanal, quantidade_mensal, data_registro)
VALUES
("30", "30", "30", "2025-06-17" );


 SELECT * FROM REFEICAO;
 SELECT * FROM DESPERDICIO;

 SELECT *
FROM    DESPERDICIO D,
REFEICAO    R
WHERE   date_format(D.DATA_REGISTRO, '%Y-%m-%d') = date_format(R.DATA_REGISTRO, '%Y-%m-%d');
 
update refeicao
set data_registro = "2025-06-11 14:23:01"
where id = 10;

update desperdicio
set data_registro = "2025-06-11 14:23:01"
where id = 22;

insert into desperdicio(DESPERDICIO_KG, RA)
values('5kg','3443');

SELECT *
FROM  DESPERDICIO D,
            REFEICAO    R
WHERE       date_format(D.DATA_REGISTRO, '%Y-%m-%d') = date_format(R.DATA_REGISTRO, '%Y-%m-%d');

select * from desperdicio;
select * from refeicao;

SELECT  D.DESPERDICIO_KG,
            D.DATA_REGISTRO
FROM  DESPERDICIO D
UNION
SELECT      R.QUANTIDADE_DIARIA,
            R.DATA_REGISTRO
FROM  REFEICAO R;

SELECT * FROM REFEICAO;
DROP TABLE CARDAPIO;
CREATE TABLE CARDAPIO (
  ID  INTEGER AUTO_INCREMENT PRIMARY KEY,
  SEMANA_REFERENCIA DATE NOT NULL, -- Ex: sempre a segunda-feira da semana
  DIA_SEMANA ENUM('segunda', 'terca', 'quarta', 'quinta', 'sexta') NOT NULL,
  BEBIDA_MANHA VARCHAR(100),
  LANCHE_MANHA VARCHAR(100),
  ACOMPANHAMENTO_MANHA VARCHAR(100),
  FRUTA_MANHA VARCHAR(100),
  ALMOCO TEXT,
  BEBIDA_TARDE VARCHAR(100),
  LANCHE_TARDE VARCHAR(100),
  ACOMPANHAMENTO_TARDE VARCHAR(100),
  FRUTA_TARDE VARCHAR(100),
  UNIQUE (SEMANA_REFERENCIA, DIA_SEMANA)
);
ALTER TABLE CARDAPIO
ADD COLUMN data DATE NOT NULL;

SELECT * FROM CARDAPIO;
TRUNCATE TABLE CARDAPIO;
TRUNCATE TABLE DESPERDICIO;
TRUNCATE TABLE REFEICAO;
SELECT * FROM DESPERDICIO;
INSERT INTO CONTAGEM_ALUNOS
(QUANTIDADE_ALUNO, PERIODO, QUANTIDADE_LANCHE, QUANTIDADE_BEBIDA, QUANTIDADE_ACOMPANHAMENTO, DATA, TURMA)
VALUES 
("30", "MANHA", "50", "20", "10", "2025-03-17", "9°EF"),
("31", "TARDE", "47", "17", "9", "2025-03-19", "7°EF"),
("32", "INTEGRAL", "53", "23", "15", "2025-03-20", "5°EF"),
("29", "INTEGRAL", "40", "15", "8", "2025-03-21", "1°EM"),
("30", "MANHA", "50", "20", "10", "2025-03-22", "9°EF"),
("31", "TARDE", "47", "17", "9", "2025-03-23", "8°EF"),
("32", "INTEGRAL", "53", "23", "15", "2025-03-24", "1°EF"),
("29", "INTEGRAL", "40", "15", "8", "2025-03-25", "2°EM"),
("30", "MANHA", "52", "25", "11", "2025-03-26", "3°EM"),
("30", "MANHA", "52", "25", "11", "2025-03-27", "4°EF");

INSERT INTO RESTRICAO_ALIMENTAR
(NOME_ALUNO, OBS, TIPO_RESTRICAO, ATESTADO_MEDICO)
VALUES
("ANA GOMES", "Intolerância ao glúten, evitar alimentos com glúten.", "CELÍACA", "ATESTADO1.PDF"),
("LUCAS GOMES", "Intolerância à lactose, evitar produtos lácteos.", "LACTOSE", "ATESTADO2.PDF"),
("PEDRO OLIVEIRA", "Alergia ao milho, evitar derivados.", "MILHO", "ATESTADO3.PDF"),
("BIANCA PIRES", "Alergia à clara do ovo.", "CLARA DO OVO", "ATESTADO4.PDF"),
("HELENA GONÇALVEZ", "Alergia ao ovo.", "OVO", "ATESTADO5.PDF"),
("ANA PAULA SILVA", "Intolerância ao glúten, evitar alimentos com glúten.", "CELÍACA", "ATESTADO6.PDF"),  
("CARLOS EDUARDO LIMA", "Intolerância à lactose, evitar produtos lácteos.", "LACTOSE", "ATESTADO7.PDF"),  
("MARIA FERNANDA COSTA", "Alergia ao milho, evitar derivados.", "MILHO", "ATESTADO8.PDF"),  
("RICARDO SOUZA MENDES", "Alergia à clara do ovo.", "CLARA DO OVO", "ATESTADO9.PDF"),  
("LUIZA MARTINS PEREIRA", "Alergia ao ovo.", "OVO", "ATESTADO10.PDF");  

INSERT INTO ADMINISTRADOR
(CPF, TIPO, NOME, EMAIL, UNIDADE_ESCOLAR, SENHA)
VALUES
("68347201934", "NUTRICIONISTA", "JOÃO SILVA", "joao.silva@email.com", "SESI São Paulo", "A7b!f3Zk9"),
("12938476528", "AUXILIAR_COZINHA", "MARIA SOUZA", "maria.souza@email.com", "SESI Rio de Janeiro", "A7b!f3Zk9"),
("58623901457", "NUTRICIONISTA", "PEDRO PEREIRA", "pedro.pereira@email.com", "SESI Belo Horizonte", "M4p#L2oR9"),
("97286140325", "NUTRICIONISTA", "ANA COSTA", "ana.costa@email.com", "SESI Campinas", "J6gH!u9Wq"),
("53067298104", "AUXILIAR_COZINHA", "CARLOS ALMEIDA", "carlos.almeida@email.com", "SESI Curitiba", "D2z&V3oR7"),
("53987462011", "NUTRICIONISTA", "LUCAS PEREIRA", "lucas.pereira@email.com", "SESI São Paulo", "rT9$kF2aP!1"),  
("47201958374", "AUXILIAR_COZINHA", "JULIANA ALMEIDA", "juliana.almeida@email.com", "SESI Rio de Janeiro", "8uVz7#bTqL5"),  
("10294857639", "NUTRICIONISTA", "GABRIELA SOUZA", "gabriela.souza@email.com", "SESI Belo Horizonte", "Jz4!Wq1PpV9"),  
("91520384761", "NUTRICIONISTA", "VITOR HENRIQUE LIMA", "vitor.henrique.lima@email.com", "SESI Campinas", "Fm6@TgX3rR8"),  
("68432019587", "AUXILIAR_COZINHA", "BEATRIZ FERNANDES", "beatriz.fernandes@email.com", "SESI Curitiba", "3aG#lV5zXw2");  

INSERT INTO DESPERDICIO
(DESPERDICIO_DIARIO, DESPERDICIO_SEMANAL, DESPERDICIO_MENSAL, RA)
VALUES
("20KG", "10KG", "10KG", "1834");

INSERT INTO REFEICAO
(quantidade_diaria, quantidade_semanal, quantidade_mensal)
VALUES
("30", "30", "30" ),
("35", "38", "40"),
("45", "60", "80"),
("50", "70", "100" );

INSERT INTO CONTAGEM_ALUNOS 
(QUANTIDADE_LANCHE_MANHA, QUANTIDADE_BEBIDA_MANHA, QUANTIDADE_LANCHE_TARDE, QUANTIDADE_BEBIDA_TARDE, TURMA, DATA, cpf_usuario)
VALUES 
(40, 30, 12, 15, '6º Ano EF2 A', '2025-06-24', '12345678923'),
(40, 30, 12, 15, '6º Ano EF2 B', '2025-06-24', '12345678923'),
(40, 30, 12, 15, '7º Ano EF2 A', '2025-06-24', '12345678923'),
(40, 30, 12, 15, '7º Ano EF2 B', '2025-06-24', '12345678923'),
(40, 30, 12, 15, '8º Ano EF2 A', '2025-06-24', '12345678923'),
(40, 30, 12, 15, '8º Ano EF2 B', '2025-06-24', '12345678923'),
(40, 30, 12, 15, '9º Ano EF2 A', '2025-06-24', '12345678923'),
(40, 30, 12, 15, '9º Ano EM B', '2025-06-24', '12345678923'),
(40, 30, 12, 15, '1º Ano EM A', '2025-06-24', '12345678923'),
(40, 30, 12, 15, '1º Ano EM B', '2025-06-24', '12345678923'),
(40, 30, 12, 15, '2º Ano EM A', '2025-06-24', '12345678923'),
(40, 30, 12, 15, '2º Ano EM B', '2025-06-24', '12345678923'),
(40, 30, 12, 15, '3º Ano EM A', '2025-06-24', '12345678923');
TRUNCATE TABLE CONTAGEM_ALUNOS;

DELETE FROM CONTAGEM_ALUNOS WHERE ID = 20;
SELECT * FROM CONTAGEM_ALUNOS;

SELECT * FROM REFEICAO;
/*CONTAGEM_ALUNOS*/

SELECT * FROM CONTAGEM_ALUNOS;
 SELECT * FROM ADMINISTRADOR;
SELECT *
 FROM CONTAGEM_ALUNOS WHERE PERIODO = 'MANHA';
 
SELECT PERIODO, COUNT(*) AS TOTAL_ALUNOS 
FROM CONTAGEM_ALUNOS GROUP BY PERIODO;

SELECT * 
FROM CONTAGEM_ALUNOS ORDER BY QUANTIDADE_ALUNO DESC;

SELECT TURMA, AVG(QUANTIDADE_LANCHE) AS MEDIA_LANCHES
 FROM CONTAGEM_ALUNOS GROUP BY TURMA;
SELECT * 
FROM CONTAGEM_ALUNOS WHERE PERIODO = 'INTEGRAL';

SELECT PERIODO, SUM(QUANTIDADE_BEBIDA) AS TOTAL_BEBIDAS
 FROM CONTAGEM_ALUNOS GROUP BY PERIODO;
 
SELECT * 
FROM CONTAGEM_ALUNOS WHERE QUANTIDADE_ALUNO > 30;

SELECT *
 FROM CONTAGEM_ALUNOS ORDER BY QUANTIDADE_ACOMPANHAMENTO DESC LIMIT 1;
 
SELECT * 
FROM CONTAGEM_ALUNOS WHERE DATA BETWEEN '2025-03-01' AND '2025-03-31';

SELECT SUM(QUANTIDADE_ALUNO) AS TOTAL_ALUNOS
 FROM CONTAGEM_ALUNOS;

/*RESTRICAO_ALIMENTAR*/
SELECT *
 FROM RESTRICAO_ALIMENTAR;
 
SELECT COUNT(*) AS TOTAL_LACTOSE
 FROM RESTRICAO_ALIMENTAR WHERE TIPO_RESTRICAO = 'LACTOSE';
 
SELECT * 
FROM RESTRICAO_ALIMENTAR WHERE TIPO_RESTRICAO LIKE '%OVO%';


SELECT * 
FROM RESTRICAO_ALIMENTAR ORDER BY LENGTH(NOME_ALUNO) DESC LIMIT 1;

SELECT DISTINCT TIPO_RESTRICAO 
FROM RESTRICAO_ALIMENTAR;

SELECT TIPO_RESTRICAO, COUNT(*) AS TOTAL
 FROM RESTRICAO_ALIMENTAR GROUP BY TIPO_RESTRICAO;
 
SELECT *
 FROM RESTRICAO_ALIMENTAR WHERE NOME_ALUNO LIKE 'A%';
 
SELECT * 
FROM RESTRICAO_ALIMENTAR ORDER BY NOME_ALUNO;

SELECT NOME_ALUNO, COUNT(*)
 FROM RESTRICAO_ALIMENTAR GROUP BY NOME_ALUNO HAVING COUNT(*) > 1;
 
 SELECT MAX(LENGTH(OBS)) AS MAIOR_OBS 
 FROM RESTRICAO_ALIMENTAR;



/*ADMINISTRADOR*/
SELECT * 
FROM ADMINISTRADOR;

SELECT COUNT(*) AS TOTAL_NUTRICIONISTAS 
FROM ADMINISTRADOR WHERE TIPO = 'NUTRICIONISTA';

SELECT *
 FROM ADMINISTRADOR WHERE TIPO = 'AUXILIAR_COZINHA';
 
SELECT * 
FROM ADMINISTRADOR ORDER BY NOME;

SELECT COUNT(DISTINCT UNIDADE_ESCOLAR) AS TOTAL_UNIDADES 
FROM ADMINISTRADOR;

SELECT *
 FROM ADMINISTRADOR ORDER BY LENGTH(EMAIL) DESC LIMIT 1;
 
SELECT UNIDADE_ESCOLAR, COUNT(*) 
FROM ADMINISTRADOR GROUP BY UNIDADE_ESCOLAR HAVING COUNT(*) > 1;

SELECT NOME, CPF 
FROM ADMINISTRADOR;

SELECT COUNT(*) AS TOTAL_ADMINISTRADORES 
FROM ADMINISTRADOR;



/*REFEICAO*/
SELECT * 
FROM REFEICAO WHERE DATA BETWEEN '2025-03-01' AND '2025-03-31';

SELECT *
 FROM REFEICAO ORDER BY CONSUMO_ALMOCO_KG DESC;
 
SELECT NUTRICIONISTA_RESPONSAVEL, COUNT(*) AS TOTAL_REFEICOES
 FROM REFEICAO GROUP BY NUTRICIONISTA_RESPONSAVEL;
 
SELECT * 
FROM REFEICAO WHERE ACOMPANHAMENTO_MANHA IS NULL OR ACOMPANHAMENTO_MANHA = '';

SELECT NUTRICIONISTA_RESPONSAVEL, SUM(CONSUMO_ALMOCO_KG) AS TOTAL_CONSUMO 
FROM REFEICAO GROUP BY NUTRICIONISTA_RESPONSAVEL;

SELECT DISTINCT NUTRICIONISTA_RESPONSAVEL
 FROM REFEICAO;
 
SELECT *
 FROM REFEICAO WHERE BEBIDA_MANHA LIKE 'Suco%';
 
SELECT * 
FROM REFEICAO WHERE LANCHE_TARDE IS NULL OR LANCHE_TARDE = '';

SELECT AVG(CONSUMO_ALMOCO_KG) AS MEDIA_CONSUMO 
FROM REFEICAO;

SELECT * 
FROM REFEICAO WHERE ALMOCO LIKE '%Feijoada%';

SELECT * FROM REFEICAO;



/*DESPERDICIO*/
SELECT * 
FROM DESPERDICIO;

SELECT * 
FROM DESPERDICIO ORDER BY CAST(REPLACE(DESPERDICIO_KG, 'KG', '') AS UNSIGNED) DESC;

SELECT SUM(CAST(REPLACE(DESPERDICIO_KG, 'KG', '') AS UNSIGNED)) AS TOTAL_DESPERDICIO
 FROM DESPERDICIO;
 
 SELECT COUNT(*) AS TOTAL_REGISTROS 
 FROM DESPERDICIO;

SELECT * 
FROM DESPERDICIO WHERE CAST(REPLACE(DESPERDICIO_KG, 'KG', '') AS UNSIGNED) > 5;

SELECT AVG(CAST(REPLACE(DESPERDICIO_KG, 'KG', '') AS UNSIGNED)) AS MEDIA_DESPERDICIO 
FROM DESPERDICIO;

SELECT * 
FROM DESPERDICIO ORDER BY CAST(REPLACE(DESPERDICIO_KG, 'KG', '') AS UNSIGNED) DESC LIMIT 1;

SELECT * 
FROM DESPERDICIO WHERE CAST(REPLACE(DESPERDICIO_KG, 'KG', '') AS UNSIGNED) BETWEEN 2 AND 7;

SELECT COUNT(DISTINCT DESPERDICIO_KG) AS VARIACOES_DESPERDICIO 
FROM DESPERDICIO;

SELECT * 
FROM DESPERDICIO ORDER BY RA;




/* 20 SELECTS COM INTEGRAÇÃO*/
SELECT RA, NOME_ALUNO, TIPO_RESTRICAO, DESPERDICIO_KG
FROM RESTRICAO_ALIMENTAR
LEFT JOIN DESPERDICIO ON RESTRICAO_ALIMENTAR.NOME_ALUNO LIKE CONCAT('%', DESPERDICIO.RA, '%');

SELECT ADMINISTRADOR.NOME, COUNT(REFEICAO.ID) AS TOTAL_REFEICOES
FROM ADMINISTRADOR
JOIN REFEICAO ON ADMINISTRADOR.NOME = REFEICAO.NUTRICIONISTA_RESPONSAVEL
WHERE ADMINISTRADOR.TIPO = 'NUTRICIONISTA'
GROUP BY ADMINISTRADOR.NOME;

SELECT CONTAGEM_ALUNOS.PERIODO, SUM(CONTAGEM_ALUNOS.QUANTIDADE_ALUNO) AS TOTAL_ALUNOS, 
       SUM(CAST(REPLACE(DESPERDICIO.DESPERDICIO_KG, 'KG', '') AS UNSIGNED)) AS TOTAL_DESPERDICIO
FROM CONTAGEM_ALUNOS
LEFT JOIN DESPERDICIO ON CONTAGEM_ALUNOS.QUANTIDADE_ALUNO = DESPERDICIO.RA
GROUP BY CONTAGEM_ALUNOS.PERIODO;

SELECT RA.NOME_ALUNO, RA.TIPO_RESTRICAO, R.NUTRICIONISTA_RESPONSAVEL
FROM RESTRICAO_ALIMENTAR RA
JOIN REFEICAO R ON RA.TIPO_RESTRICAO LIKE CONCAT('%', R.ALMOCO, '%');

SELECT D.DESPERDICIO_KG, R.DATA, R.ALMOCO
FROM DESPERDICIO D
JOIN REFEICAO R ON D.RA = R.ID;

SELECT R.NUTRICIONISTA_RESPONSAVEL, COUNT(R.ID) AS TOTAL_REFEICOES,
       SUM(CAST(REPLACE(D.DESPERDICIO_KG, 'KG', '') AS UNSIGNED)) AS TOTAL_DESPERDICIO
FROM REFEICAO R
LEFT JOIN DESPERDICIO D ON R.ID = D.RA
GROUP BY R.NUTRICIONISTA_RESPONSAVEL;

SELECT A.NOME, R.DATA, R.ALMOCO
FROM ADMINISTRADOR A
JOIN REFEICAO R ON A.NOME = R.NUTRICIONISTA_RESPONSAVEL
WHERE A.TIPO = 'NUTRICIONISTA';

SELECT RA.NOME_ALUNO, RA.TIPO_RESTRICAO, R.BEBIDA_MANHA, R.BEBIDA_TARDE
FROM RESTRICAO_ALIMENTAR RA
JOIN REFEICAO R ON RA.TIPO_RESTRICAO LIKE CONCAT('%', R.BEBIDA_MANHA, '%');

SELECT CA.TURMA, CA.DATA, R.ALMOCO
FROM CONTAGEM_ALUNOS CA
JOIN REFEICAO R ON CA.DATA = R.DATA;

SELECT R.NUTRICIONISTA_RESPONSAVEL, AVG(CAST(R.CONSUMO_ALMOCO_KG AS DECIMAL(10,2))) AS MEDIA_CONSUMO
FROM REFEICAO R
GROUP BY R.NUTRICIONISTA_RESPONSAVEL;

SELECT D.RA, D.DESPERDICIO_KG, RA.NOME_ALUNO, RA.TIPO_RESTRICAO
FROM DESPERDICIO D
LEFT JOIN RESTRICAO_ALIMENTAR RA ON D.RA = RA.NOME_ALUNO;

SELECT CA.PERIODO, SUM(CAST(REPLACE(D.DESPERDICIO_KG, 'KG', '') AS UNSIGNED)) AS TOTAL_DESPERDICIO
FROM CONTAGEM_ALUNOS CA
JOIN DESPERDICIO D ON CA.QUANTIDADE_ALUNO = D.RA
GROUP BY CA.PERIODO
ORDER BY TOTAL_DESPERDICIO DESC;

SELECT RA.NOME_ALUNO, CA.TURMA, CA.DATA
FROM RESTRICAO_ALIMENTAR RA
LEFT JOIN CONTAGEM_ALUNOS CA ON RA.NOME_ALUNO LIKE CONCAT('%', CA.TURMA, '%');

SELECT DISTINCT UNIDADE_ESCOLAR, COUNT(*) AS TOTAL_ADMINISTRADORES
FROM ADMINISTRADOR
GROUP BY UNIDADE_ESCOLAR;

SELECT R.DATA, R.ALMOCO, D.DESPERDICIO_KG
FROM REFEICAO R
LEFT JOIN DESPERDICIO D ON R.DATA = (SELECT DATA FROM CONTAGEM_ALUNOS WHERE CONTAGEM_ALUNOS.TURMA = D.RA);

SELECT D.RA, D.DESPERDICIO_KG, CA.TURMA
FROM DESPERDICIO D
JOIN CONTAGEM_ALUNOS CA ON D.RA = CA.QUANTIDADE_ALUNO
WHERE CAST(REPLACE(D.DESPERDICIO_KG, 'KG', '') AS UNSIGNED) > 5;

SELECT SUM(QUANTIDADE_ALUNO) AS TOTAL_ALUNOS,
       AVG(CAST(REPLACE(DESPERDICIO_KG, 'KG', '') AS UNSIGNED)) AS MEDIA_DESPERDICIO
FROM CONTAGEM_ALUNOS
JOIN DESPERDICIO ON CONTAGEM_ALUNOS.QUANTIDADE_ALUNO = DESPERDICIO.RA;

SELECT CA.TURMA, SUM(CA.QUANTIDADE_LANCHE) AS TOTAL_LANCHES, SUM(CA.QUANTIDADE_ALUNO) AS TOTAL_ALUNOS
FROM CONTAGEM_ALUNOS CA
GROUP BY CA.TURMA
ORDER BY TOTAL_LANCHES DESC;

SELECT A.NOME, SUM(CAST(REPLACE(D.DESPERDICIO_KG, 'KG', '') AS UNSIGNED)) AS TOTAL_DESPERDICIO
FROM ADMINISTRADOR A
JOIN REFEICAO R ON A.NOME = R.NUTRICIONISTA_RESPONSAVEL
LEFT JOIN DESPERDICIO D ON R.ID = D.RA
WHERE A.TIPO = 'NUTRICIONISTA'
GROUP BY A.NOME;

SELECT CA.PERIODO, COUNT(*) AS TOTAL_REFEICOES
FROM CONTAGEM_ALUNOS CA
JOIN REFEICAO R ON CA.DATA = R.DATA
GROUP BY CA.PERIODO;



#DATA DE HOJE
SELECT SUM(QUANTIDADE_DIARIA) FROM REFEICAO
WHERE date_format(NOW(), '%d-%m-%Y') = date_format(DATA_REGISTRO, '%d-%m-%Y');

SELECT SUM(DESPERDICIO_KG) FROM DESPERDICIO
WHERE date_format(NOW(), '%d-%m-%Y') = date_format(DATA_REGISTRO, '%d-%m-%Y');

#MES
SELECT * FROM REFEICAO
WHERE date_format(NOW(), '%m') = date_format(DATA_REGISTRO, '%m');

SELECT sum(quantidade_mensal) as quantidade_mensal FROM REFEICAO
WHERE date_format(NOW(), '%m') = date_format(DATA_REGISTRO, '%m');

#SEMANA
SELECT * FROM REFEICAO
WHERE WEEK(NOW())=WEEK(DATA_REGISTRO)